import { UserRole } from './types/entities';

export type Capability =
  | 'VIEW_OWN_EMPLOYEE'
  | 'VIEW_ALL_EMPLOYEES'
  | 'MANAGE_EMPLOYEES'
  | 'VIEW_OWN_ATTENDANCE'
  | 'VIEW_ALL_ATTENDANCE'
  | 'MANUAL_ATTENDANCE_CORRECTION'
  | 'CREATE_TIME_OFF_REQUEST'
  | 'APPROVE_TIME_OFF'
  | 'MANAGE_TIME_OFF_TYPES'
  | 'MANAGE_CONTRACTS_SCHEDULES'
  | 'VIEW_OWN_PAYSLIPS'
  | 'VIEW_ALL_PAYSLIPS'
  | 'VIEW_PAYRUNS'
  | 'PROCESS_PAYRUNS'
  | 'VALIDATE_PAYRUNS'
  | 'VIEW_SALARY_STRUCTURES'
  | 'MANAGE_SALARY_RULES'
  | 'VIEW_PAYROLL_DASHBOARD'
  | 'VIEW_TEAM_DIRECTORY'
  | 'USER_MANAGEMENT';

export const RBAC_MATRIX: Record<Capability, UserRole[]> = {
  VIEW_OWN_EMPLOYEE: [
    'EMPLOYEE',
    'HR_MANAGER',
    'HR_PAYROLL_USER',
    'HR_PAYROLL_MANAGER',
    'ADMIN',
  ],
  VIEW_ALL_EMPLOYEES: ['HR_MANAGER', 'HR_PAYROLL_USER', 'HR_PAYROLL_MANAGER', 'ADMIN'],
  MANAGE_EMPLOYEES: ['HR_MANAGER', 'HR_PAYROLL_USER', 'HR_PAYROLL_MANAGER', 'ADMIN'],
  VIEW_OWN_ATTENDANCE: [
    'EMPLOYEE',
    'HR_MANAGER',
    'HR_PAYROLL_USER',
    'HR_PAYROLL_MANAGER',
    'ADMIN',
  ],
  VIEW_ALL_ATTENDANCE: ['HR_MANAGER', 'HR_PAYROLL_USER', 'HR_PAYROLL_MANAGER', 'ADMIN'],
  MANUAL_ATTENDANCE_CORRECTION: ['HR_MANAGER', 'HR_PAYROLL_USER', 'HR_PAYROLL_MANAGER', 'ADMIN'],
  CREATE_TIME_OFF_REQUEST: [
    'EMPLOYEE',
    'HR_MANAGER',
    'HR_PAYROLL_USER',
    'HR_PAYROLL_MANAGER',
    'ADMIN',
  ],
  APPROVE_TIME_OFF: ['HR_MANAGER', 'HR_PAYROLL_USER', 'HR_PAYROLL_MANAGER', 'ADMIN'],
  MANAGE_TIME_OFF_TYPES: ['HR_MANAGER', 'HR_PAYROLL_USER', 'HR_PAYROLL_MANAGER', 'ADMIN'],
  MANAGE_CONTRACTS_SCHEDULES: ['HR_MANAGER', 'HR_PAYROLL_USER', 'HR_PAYROLL_MANAGER', 'ADMIN'],
  VIEW_OWN_PAYSLIPS: [
    'EMPLOYEE',
    'HR_MANAGER',
    'HR_PAYROLL_USER',
    'HR_PAYROLL_MANAGER',
    'ADMIN',
  ],
  VIEW_ALL_PAYSLIPS: ['HR_MANAGER', 'HR_PAYROLL_USER', 'HR_PAYROLL_MANAGER', 'ADMIN'],
  VIEW_PAYRUNS: ['HR_PAYROLL_USER', 'HR_PAYROLL_MANAGER', 'ADMIN'],
  PROCESS_PAYRUNS: ['HR_PAYROLL_USER', 'HR_PAYROLL_MANAGER', 'ADMIN'],
  VALIDATE_PAYRUNS: ['HR_PAYROLL_USER', 'HR_PAYROLL_MANAGER', 'ADMIN'],
  VIEW_SALARY_STRUCTURES: ['HR_PAYROLL_USER', 'HR_PAYROLL_MANAGER', 'ADMIN'],
  MANAGE_SALARY_RULES: ['HR_PAYROLL_MANAGER', 'ADMIN'],
  VIEW_PAYROLL_DASHBOARD: ['HR_PAYROLL_USER', 'HR_PAYROLL_MANAGER', 'ADMIN'],
  VIEW_TEAM_DIRECTORY: [
    'EMPLOYEE',
    'HR_MANAGER',
    'HR_PAYROLL_USER',
    'HR_PAYROLL_MANAGER',
    'ADMIN',
  ],
  USER_MANAGEMENT: ['ADMIN'],
};

export function can(role: UserRole, capability: Capability): boolean {
  return RBAC_MATRIX[capability].includes(role);
}
